language: java
script: mvn test -B
deploy:
  provider: heroku
  api_key:
    secure: aOXmH37MbNs8HC9aeTKJ7XTCDfgV1a9gRZVkgt6v8pD3oEs4b9riUQJmlLvPdhrmw9YDeAR3vuic2I4O3vs9nkdgXDAIcK4l/Z7vdggKVDu8EQgftcOHDhn5AS/9a3qvzF81oo3/Wsz0aDtyPcqrqCDTRf1sGcNB3Ng6kBtJPY5Lm33nWC9vf7+xi3uNY+Lnj8ySshGBVXyV/9FOnfPDi5oO5sho1BLFhJo9YiRxI/KINqpeWRJjTnLQ98weIXxGIzCt277LDJGKKpqWPAwdvyM4yvSBHaIoFnsdTcgsdwZ0lSu9lG9fPXF8w1JdcbH21JChn1/nbq0moJqcD0oqaUWg8cRgODRJaQaSPBT0va69S7zl8I/XEM+jAamd/P8Cgjr/OUNWegfBI8r+ku3U9u8dkvnjDhCiG7+73uYKgFWSQdmkCEnn2aGvFtfCiR/gU80UNHsxmR//fqUkuKYHBI9dR20aYZ/058HjdvFnHIrBlo+CY6fDYQYp0q+USQehimUXtFee3MIXOKUG+UJUtsOoavEBMa08r3dbqlbBPbkj4Wctz1gKQCd1x2hKEvKLbF4k4ESSsv4x8e/yB/oFwoXSuhsIMXDJQ4yBr7vW9u999BHN4bnloEWmhIUCdoj0LsWyjDJhxYrYKcvqdy8tkIwuTsdLlBF64RCAaFeshpQ=
  app: pruebaavengers
  on:
    repo: RubenPerez95/PruebaAvengers
