sudo: false
language: java
script: mvn test -B
deploy:
  provider: heroku
  api_key:
    secure: bs1syijy9inLT/79ydGH7MmXdzqSGMuRapduvyp+8e8sFZSmsSLqNqhZl00qMIqD+QC7YHyvyOx/Z8dzsOLSC0yKJhbPOWdDUJqpDDciFOVqsK0NJc2NA1c/LtdTNLwga9iVIeUEkqVpvzWj1A5JV9RjNd2q2qGejTOeXVAHgI/bsmOp5uZJh+FCmZBwKzuvbk9IlinUoQROScyPi8dGXZkLu/L4Z5hD7R9E7xGaoFNycHyTLD6z3oITnymluO/onDTDjCKNm6oHZ8KqBGMAXfp396hnbcztMx+GPqi3GbkFbCwa7R4uTnt6G/I0zutp6CvOBtTGeLSiT60gauf9l6XSb1c1CvKJhXYpSTCoPlQ2zsAwQ8lGr9rFF3NBSXeE/ayPyrkrP3X5TjF653m8IOL5MuJq1GTw8leK6REnQMVDsbOuh6ase86yA1MCv9IrUcHbeBiikNEkwjj3EquZ+AYIldZm+PYBg1xHDCcO+/Oi9CJhWlF/OWOk6pXYz88BkgJGppJGVPuwjDu3A57yoWb9t7jK85w4GhR2pr3J6TSR/DJLnklQbe7XqojCX92yUkiHXT7xBlfp6yIPlIL5rH0GXjmAGEUg6Fx6EUJzyBJ6YMLGV05AZEGUZaFKTkF063+ss4eQbdy0orzbZgxHUcxHVajbc7Y/BuoZbxsPG0I=
  app: pruebaavengers
  on:
    repo: RubenPerez95/PruebaAvengers
