language: java
script: mvn test -B
deploy:
  provider: heroku
  api_key:
    secure: c29+bRtDgVIemi/TaGV8RzPIodXkabxymVUiuJHKs9JcPhZUZBa1iaJ5mDKTPPnDVkvSBym2moPHNB8s0opr2KN5Mg+gO4YUKKNa2fYx8pOg+g89ZQ34bM8loYtTfXAzWYoKJv3sFDWjxKMkpDCzHOLxPql+9MeLJRRzX0/CTIzaP4xyyVQhnH4jxwt/y1nad5gQz0i9LXZ8Ry03osjcBEWXk4XHP43dnyky9dVvUK8ET6dK3pp3fD4a2Ejzf325Shx/+dLhyLqGy68GBpKqU2Ni6uKXwRV8oHTkiCj5yWTwBhiYU2ADU5hSqKFajMIeCzNQbKAyzysbLMMWwLgsdDiRzXFAQDKGk3TmZSbXEHcz8xz77qSPV5b6Ehb9Wzy0XKW/Xa/9QFz5JE2Fh7bni+etlJ3o+skGFTonpYEa2WlUlty7A5rcWQgW35xoWpIgpVwjOdouMIEl31gy+37knu0fU+SsaMz6qP/oSMsSzSVIf3h8qGKryrTxe5A7+NVDIxlE2VbfIF8GDQG4Da/h0Su3zqKZJxUmkeRIEec5F0on/Rp3wzeQh5tlEex4sc0czpbBWPIaQYBYeiMGpGdh+vjMJ2u0xtZsOp5EowpOMkcitSRJr8EHkRfN7KVMdWlcDAwOxf6weghkECQ9hDsH0WwlYlrIsqwVCApUeTO6Cgk=
  app: pruebaavengers
  on:
    repo: RubenPerez95/PruebaAvengers
