language: java
script: mvn test -B
deploy:
  provider: heroku
  api_key:
    secure: 1nWpgTuZhuqY/OJle4TMwVraI+ncfUGyQ7KFr69DfPml0VG+9jISfH9j8UbJtmu8LSmW30W37r9lOKaBJzOFnOK0In6W1rfLiBX66pD8QbNNWhhzpUOGhgNGphPKiI7Xei21e4CiwCW9W2SXN9p7x/Y/X1bwj+oGTzqgEdpe6rVfeTDAgysxuH15nsVYz0Rq//r2MI8vsV1C9psPhHIThSotnHIASqnX8vm9zpzgJmUpBrcC7Aml/ZYYzlrmSpqAZLCFL8SjegcUDTjy8sa8MVk4hfb2e7JThnRbqW03HxSZPEbU8rxwSykxUBmkhyQaSAfLrAaOi6T/9+XfUI0kq0Isc2Mb3vMQsDAnnJKlYHSb9uaSOsIJjam/30940ABy4vt9CEHhxEBnTwGiuf0RzBKjZZtkWH+vI/eUeMYLNAVIYNT8dvzaEXEk9o/q9uxrVuVDyrZ4T5+6XLGkAnZa7YssQ1b2Mm7wLOH9+vHaXN5RoejtLsKdo7EUyrXAePCPlo0hYH5WoyFpkKnwaw2HJatgRicFq1pNnAbPbEpfDf2WbnGPBcggAONdSAEw/UA+mdSCgCfd9xo6S3zmDG6ZnvsEuWSDF/8dI71iZQ8obtaHS9R6sPb7Dx28qsHPpOKL3y2e4FrgvS2ygRvRyXxsqHx7iBbZo6ZkJ39QZXSWT0Y=
  app: pruebaavengers
  on:
    repo: RubenPerez95/PruebaAvengers
